spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:geospotdb}
    username: ${DB_USER:usrgeospot}
    password: ${DB_PASSWORD:pwdgeospot}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:7IRKF6Rh1kGSAfKt5jEBOmJ+AKWxYJVm4uLuxobk7Bk=}
  expiration: 900000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    context-path: /geospot/api

geoapify:
  api-key: ${GEOAPIFY_API_KEY:d1be425fcf044191b4d1354bb1fc6059}